//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldoon.WindowsService.Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Store { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Status { get; set; }
    }

    public partial class Queue_Payment
    {
        public int Id { get; set; }
        public string Store { get; set; }
        public int OrderId { get; set; }
        public int Price { get; set; }
        public int Status { get; set; }
        public string RefId { get; set; }

    }



}
